month=int(input("Enter number from 1 to 12:"))
if month==1:
    print("31 days")
elif month==2:
    print("28/29 days")
elif month==3:
    print("31 days")
elif month==4:
    print("30 days")
elif month==5:
    print("31 days")
elif month==6:
    print("30 days")
elif month==7:
    print("31 days")
elif month==8:
    print("30 days")
elif month==9:
    print("31 days")
elif month==10:
    print("30 days")
elif month==11:
    print("31 days")
elif month==12:
    print("30 days")